# For more information: https://laravel.com/docs/sail
version: '3'
services:
    nginx:
        container_name: test_review_nginx
        restart: always
        build:
            context: ./docker/prod/nginx
            dockerfile: Dockerfile
        depends_on:
            - php-fpm
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - "./docker/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./.:/app/"
        networks:
            - sail
    php-fpm:
        container_name: test_review_fpm
        restart: always
        build:
            context: ./docker/prod/php
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        environment:
            WWWUSER: '${WWWUSER}'
        depends_on:
            - mariadb
        volumes:
            - ".:/app"
        networks:
            - sail
    mariadb:
        container_name: test_review_mariadb
        restart: always
        image: 'mariadb:latest'
        ports:
            - '${FORWARD_DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mariadb:
        driver: local
